apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:b742447c17f96e8d220e0ab19085bf236e929a93
        ports:
        - containerPort: 80
