apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 905418310012.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:606ebd7d22f59f50b4a352bf54ef2f79f234f288
        ports:
        - containerPort: 80
