apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-earphones:b742447c17f96e8d220e0ab19085bf236e929a93
        ports:
        - containerPort: 80
