apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: 905418310012.dkr.ecr.us-east-1.amazonaws.com/shopping-site-backend:606ebd7d22f59f50b4a352bf54ef2f79f234f288
          ports:
            - containerPort: 5000
