apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:b742447c17f96e8d220e0ab19085bf236e929a93
        ports:
        - containerPort: 80
