apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlepay:b742447c17f96e8d220e0ab19085bf236e929a93
        ports:
        - containerPort: 80
