apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlegrocery:b11dcb7fdad34a4a0888fd6cd8f5d6cbe0ff3fc6
        ports:
        - containerPort: 80
