apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 905418310012.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlegrocery:b742447c17f96e8d220e0ab19085bf236e929a93
        ports:
        - containerPort: 80
